// The people of Vaeloria, drawn with the heroes' paper doll (heroDoll.ts):
// one look per character of the world, keyed by the id the scenes use.

import {
  BLUE,
  CHARCOAL,
  CLOTH_BROWN,
  DARK_LEATHER,
  FOREST,
  GOLD,
  GREEN,
  IRON,
  LEATHER,
  Look,
  PURPLE,
  RED,
  STEEL,
  Tones,
  WHITE,
  WOOD,
} from './heroDoll';

const GREY_HAIR: Tones = [[226, 226, 222], [184, 184, 184], [128, 126, 134]];
const WHITE_HAIR: Tones = [[252, 252, 248], [218, 216, 214], [162, 160, 168]];
const BLACK_HAIR: Tones = [[96, 84, 90], [58, 48, 56], [36, 30, 40]];
const AUBURN: Tones = [[220, 120, 80], [170, 76, 52], [112, 46, 38]];
const BLOND: Tones = [[250, 226, 150], [222, 186, 102], [168, 130, 70]];
const STRAW: Tones = [[244, 216, 136], [212, 172, 92], [160, 118, 62]];
const OLIVE_CLOTH: Tones = [[164, 168, 110], [120, 126, 78], [80, 86, 56]];
const MARSH_CLOTH: Tones = [[140, 156, 112], [98, 114, 80], [62, 74, 56]];
const TEAL: Tones = [[110, 178, 176], [62, 130, 134], [36, 84, 92]];
const ROSE: Tones = [[230, 150, 160], [186, 96, 116], [122, 56, 80]];
const SHADOW_SKIN: Tones = [[60, 56, 74], [42, 38, 54], [28, 24, 38]];
const TAN: Tones = [[226, 170, 120], [196, 134, 92], [150, 96, 66]];
const DARK_SKIN: Tones = [[176, 120, 88], [140, 90, 64], [98, 60, 46]];
const boots = { shape: 'boots', mat: LEATHER };

export const NPC_LOOKS: Record<string, Look> = {
  villager_wanderer: {
    race: 'human',
    chest: { shape: 'tunic', mat: OLIVE_CLOTH, trim: LEATHER },
    legs: { shape: 'pants', mat: CLOTH_BROWN },
    boots,
    hair: BLACK_HAIR,
  },
  merchant_generic: {
    race: 'human',
    chest: { shape: 'apron', mat: BLUE, trim: WHITE },
    legs: { shape: 'pants', mat: CLOTH_BROWN },
    boots,
    hairStyle: 'halfling',
    beard: true,
    hair: AUBURN,
  },
  guard_generic: {
    race: 'human',
    head: { shape: 'helm', mat: IRON },
    chest: { shape: 'chain', mat: IRON, trim: BLUE },
    legs: { shape: 'greaves', mat: IRON },
    boots: { shape: 'sabatons', mat: IRON },
    main: { shape: 'spear', mat: STEEL },
    off: { shape: 'shield', mat: BLUE, trim: IRON },
  },
  farmer_generic: {
    race: 'human',
    head: { shape: 'straw', mat: STRAW, trim: RED },
    chest: { shape: 'tunic', mat: GREEN, trim: LEATHER },
    legs: { shape: 'pants', mat: CLOTH_BROWN },
    boots,
    skin: TAN,
    main: { shape: 'pitchfork', mat: IRON },
  },
  brasque_merchant: {
    race: 'dwarf',
    head: { shape: 'cap', mat: RED, trim: GOLD },
    chest: { shape: 'apron', mat: RED, trim: DARK_LEATHER },
    legs: { shape: 'pants', mat: CLOTH_BROWN },
    boots,
    hair: GREY_HAIR,
  },
  hamlet_mentor: {
    race: 'human',
    chest: { shape: 'robe', mat: CLOTH_BROWN, trim: GOLD },
    legs: { shape: 'pants', mat: CLOTH_BROWN },
    boots,
    hair: WHITE_HAIR,
    hairStyle: 'elf',
    beard: true,
    main: { shape: 'cane', mat: WOOD },
  },
  city_mage: {
    race: 'elf',
    chest: { shape: 'robe', mat: PURPLE, trim: GOLD },
    legs: { shape: 'pants', mat: PURPLE },
    boots,
    hair: WHITE_HAIR,
    main: { shape: 'staff', mat: WOOD, trim: [[200, 240, 255], [110, 190, 232], [60, 120, 180]] },
    amulet: true,
  },
  city_captain: {
    race: 'human',
    head: { shape: 'plumed', mat: STEEL, trim: RED },
    chest: { shape: 'plate', mat: STEEL, trim: RED },
    legs: { shape: 'greaves', mat: STEEL },
    boots: { shape: 'sabatons', mat: STEEL },
    gloves: { shape: 'gauntlets', mat: STEEL },
    cape: { shape: 'cape', mat: RED },
    main: { shape: 'sword', mat: STEEL, trim: GOLD },
    beard: true,
    hair: BLACK_HAIR,
  },
  gontrand_scholar: {
    race: 'human',
    chest: { shape: 'robe', mat: TEAL, trim: GOLD },
    legs: { shape: 'pants', mat: TEAL },
    boots,
    hairStyle: 'bald',
    beard: true,
    hair: GREY_HAIR,
    off: { shape: 'tome', mat: RED, trim: GOLD },
  },
  shrine_hermit: {
    race: 'human',
    head: { shape: 'hood', mat: [[170, 166, 150], [130, 126, 112], [88, 86, 80]] },
    chest: { shape: 'robe', mat: [[170, 166, 150], [130, 126, 112], [88, 86, 80]] },
    legs: { shape: 'pants', mat: CLOTH_BROWN },
    beard: true,
    hair: WHITE_HAIR,
    main: { shape: 'cane', mat: WOOD },
  },
  hunter_outpost: {
    race: 'human',
    head: { shape: 'hood', mat: FOREST },
    chest: { shape: 'leather', mat: LEATHER },
    legs: { shape: 'pants', mat: DARK_LEATHER },
    boots,
    gloves: { shape: 'bracers', mat: LEATHER },
    cape: { shape: 'cape', mat: FOREST },
    main: { shape: 'bow', mat: WOOD },
    quiver: true,
    skin: TAN,
  },
  informant_faubourg: {
    race: 'halfling',
    head: { shape: 'hood', mat: CHARCOAL },
    chest: { shape: 'jerkin', mat: DARK_LEATHER, trim: GOLD },
    legs: { shape: 'pants', mat: CHARCOAL },
    cape: { shape: 'cape', mat: CHARCOAL },
  },
  vasenoire_local_toma: {
    race: 'human',
    head: { shape: 'straw', mat: STRAW, trim: MARSH_CLOTH },
    chest: { shape: 'tunic', mat: MARSH_CLOTH, trim: LEATHER },
    legs: { shape: 'pants', mat: OLIVE_CLOTH },
    boots,
    skin: DARK_SKIN,
    hair: BLACK_HAIR,
  },
  vasenoire_local_yenn: {
    race: 'human',
    head: { shape: 'kerchief', mat: TEAL },
    chest: { shape: 'robe', mat: MARSH_CLOTH, trim: TEAL },
    legs: { shape: 'pants', mat: MARSH_CLOTH },
    boots,
    skin: DARK_SKIN,
    hairStyle: 'elf',
    hair: BLACK_HAIR,
  },
  mysterious_silhouette: {
    race: 'human',
    head: { shape: 'hood', mat: [[70, 64, 86], [44, 40, 58], [26, 22, 36]] },
    chest: { shape: 'robe', mat: [[70, 64, 86], [44, 40, 58], [26, 22, 36]] },
    legs: { shape: 'pants', mat: CHARCOAL },
    cape: { shape: 'cape', mat: [[70, 64, 86], [44, 40, 58], [26, 22, 36]] },
    skin: SHADOW_SKIN,
    eyes: [200, 150, 255],
  },
  bertrand_fisherman: {
    race: 'human',
    head: { shape: 'straw', mat: STRAW, trim: BLUE },
    chest: { shape: 'tunic', mat: BLUE, trim: LEATHER },
    legs: { shape: 'pants', mat: CLOTH_BROWN },
    boots,
    beard: true,
    hair: AUBURN,
    skin: TAN,
    main: { shape: 'rod', mat: WOOD },
  },
  fauvette_grandmother: {
    race: 'halfling',
    head: { shape: 'kerchief', mat: ROSE },
    chest: { shape: 'robe', mat: CLOTH_BROWN, trim: ROSE },
    legs: { shape: 'pants', mat: CLOTH_BROWN },
    hair: GREY_HAIR,
    main: { shape: 'cane', mat: WOOD },
  },
  fernand_innkeeper: {
    race: 'human',
    chest: { shape: 'apron', mat: RED, trim: WHITE },
    legs: { shape: 'pants', mat: CLOTH_BROWN },
    boots,
    hairStyle: 'bald',
    beard: true,
    hair: BLACK_HAIR,
  },
  ombeline_catlady: {
    race: 'human',
    chest: { shape: 'robe', mat: PURPLE, trim: ROSE },
    legs: { shape: 'pants', mat: PURPLE },
    boots,
    hair: GREY_HAIR,
    hairStyle: 'elf',
  },
  solange_weaver: {
    race: 'human',
    head: { shape: 'kerchief', mat: BLUE },
    chest: { shape: 'robe', mat: BLUE, trim: WHITE },
    legs: { shape: 'pants', mat: BLUE },
    boots,
    hair: BLOND,
    hairStyle: 'elf',
  },
  thibault_father: {
    race: 'human',
    chest: { shape: 'tunic', mat: RED, trim: LEATHER },
    legs: { shape: 'pants', mat: CLOTH_BROWN },
    boots,
    beard: true,
    hair: [[160, 110, 70], [118, 78, 48], [80, 50, 34]],
  },
};
