"""Exports the 25 hero sprite sheets and portraits generated by heroes.py.

Usage: python3 tools/art/build_heroes.py   (writes into public/sprites/heroes/)

- <race>_<class>.png: 4 columns (stepA, idle, stepB, breathe) x 4 rows
  (down, left, right, up) of 24x32 frames, 1 art pixel = 1 game pixel like
  the world.
- <race>_<class>_face.png: head and shoulders for the interface, at 2x
  (the interface's pixel size), 32x26.
"""

from pathlib import Path

from PIL import Image

import heroes

OUT = Path(__file__).resolve().parents[2] / 'public/sprites/heroes'


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for race in heroes.RACES:
        for cls in heroes.CLASSES:
            hero = heroes.Hero(race, cls)
            cols = len(heroes.COLUMNS)
            sheet = Image.new('RGBA', (heroes.W * cols, heroes.H * len(heroes.VIEWS)), (0, 0, 0, 0))
            for row, view in enumerate(heroes.VIEWS):
                for col, (step, breathe) in enumerate(heroes.COLUMNS):
                    sheet.paste(hero.frame(view, step, breathe), (col * heroes.W, row * heroes.H))
            sheet.save(OUT / f'{race}_{cls}.png')
            top = hero.rows()['head_top']
            face = hero.frame('down', 0).crop((4, top - 1, 20, top + 12))
            face.resize((face.width * 2, face.height * 2), Image.NEAREST).save(OUT / f'{race}_{cls}_face.png')
    print('ok', OUT)


if __name__ == '__main__':
    main()
